host: localhost:8090
server:
  port: 8090

spring:
  datasource:
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.3.104:63306/src_external_data?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=true&serverTimezone=Asia/Shanghai
    username: ruqi_bi
    password: G#21Sdf23rsd3#fsdf3er2
    initial-size: 5
    max-active: 20
    min-idle: 5
    max-idle: 20
    max-wait: 30000
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true

#mybatis
mybatis:
  #mapper
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lifeifei.springboot.springbootbuild.mode
  configuration:
    map-underscore-to-camel-case: true



